services:
  timescale:
    image: timescale/timescaledb-ha:pg17
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:4-alpine
    ports:
      - 5672:5672
      - 15672:15672
